version: "3.7"

services:

  flask:
    build: ./Backend2
    container_name: flask
    restart: always
    env_file:
      - prod.env
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"